Repository cloudposse/github-action-deploy-argocd, pull requests merged in 2024-07, with the labels that each got.

#59 YQ Improvement: Only one url
  action.yml
Labels: patch

#60 fix: install chamber directly instead of using a container (bypass Docker Hub rate limits)
  .github/workflows/test-destroy.yml
  .github/workflows/test-helm-raw-default-kube-version.yml
  .github/workflows/test-helm-raw.yml
  .github/workflows/test-helmfile-raw-default-kube-version.yml
  .github/workflows/test-helmfile-raw.yml
  action.yml
Labels: bugfix

#61 fix: use 'sudo' when installing the chamber binary
  action.yml
Labels: bug
